<?php

namespace AppBundle\Repository;

/**
 * MarchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchantRepository extends \Doctrine\ORM\EntityRepository
{
}
